// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Pages/Home.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as CustomTheme from "./CustomTheme.bs.js";
import * as Styles from "@material-ui/core/styles";

function str(prim) {
  return prim;
}

function $$int(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function App(Props) {
  return React.createElement(Styles.ThemeProvider, {
              children: React.createElement(Home.make, {}),
              theme: CustomTheme.theme
            });
}

var make = App;

export {
  str ,
  $$int ,
  useState ,
  make ,
  
}
/* Home Not a pure module */
