// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function str(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCounter = match[1];
  var counter = match[0];
  var inc = function (param) {
    return Curry._1(setCounter, (function (param) {
                  return counter + 1 | 0;
                }));
  };
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Counter: " + String(counter)), React.createElement("button", {
                  onClick: inc
                }, "Increment"));
}

var make = App;

export {
  str ,
  useState ,
  make ,
  
}
/* react Not a pure module */
