// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var container = document.querySelector("#root");

if (container == null) {
  console.log("No container found");
} else {
  ReactDom.render(React.createElement(App.make, {}), container);
}

var container$1 = (container == null) ? undefined : Caml_option.some(container);

export {
  container$1 as container,
  
}
/* container Not a pure module */
